#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Sebastian Linnér - .NET Developer
url: 'https://galenginger.github.io'

#change it according to your repository name
baseurl: '/OnlineCV' 

description: Online CV - Sebastian Linnér, .NET Systemutvecklare Student
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: berry # blue turquoise green berry orange ceramic teal oceanstale purple
chrome_mobile_color: #A15277

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
